---
version: '3.5'
services:

  # Nginx service
  webserver:
    image: nginx:alpine
    container_name: ego-sum-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php/src:/var/www/public/
      - ./webserver/templates:/etc/nginx/templates
      - ./webserver/conf.d:/etc/nginx/conf.d
    environment:
      HEADER_CONTENTS: 'Hello'
    networks:
      - ego-sum-net

  # Waterfall service
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: ego-sum
    container_name: ego-sum-files
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: "ego-sum"
      SERVICE_TAGS: "prod"
    working_dir: /var/www/public
    volumes:
      - ./php/src:/var/www/public
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ego-sum-net

networks:
  ego-sum-net:
    driver: bridge
    name: 'ego_sum_network'
...
